Repository parkkyonghun0510/lc-opd-daily, pull requests merged in 2025-03, with the labels that each got.

#1 Fixbugand feature032220251122
  src/app/(dashboard)/dashboard/admin/reports/pending/page.tsx
  src/app/(dashboard)/dashboard/reports/pending/page.tsx
  src/app/(dashboard)/dashboard/settings/page.tsx
  src/app/(dashboard)/dashboard/users/[id]/page.tsx
  src/app/(dashboard)/dashboard/users/page.tsx
  src/app/api/admin/system/health/route.ts
  src/app/api/reports/pending/route.ts
  src/app/api/users/[id]/profile/route.ts
  src/app/api/users/[id]/toggle-status/route.ts
  src/app/api/validation-rules/route.ts
  src/app/login/page.tsx
  src/components/admin/AdminOverview.tsx
  src/components/branch/BranchAssignmentManager.tsx
  src/components/dashboard/RoleBasedDashboard.tsx
  src/components/dashboard/layout/RoleBasedNavigation.tsx
  src/components/dashboard/layout/Sidebar.tsx
  src/components/dashboard/layout/TopBar.tsx
  src/components/forms/UserProfileForm.tsx
  src/components/forms/UserSecurityForm.tsx
  src/components/reports/CreateReportModal.tsx
  src/contexts/UserDataContext.tsx
  src/hooks/useBranchPermission.tsx
  src/hooks/useReportForm.ts
  src/lib/api/reports.ts
  src/lib/auth/options.ts
  src/lib/auth/roles.ts
Labels: bug, documentation, duplicate

#4 fix(notifications): correct model name in Prisma query
  build_log.txt
  src/app/api/notifications/[id]/read/route.ts
Labels: bug

#6 feat: enhance PWA prompts and notification handling
  src/app/api/push/validate/route.ts
  src/app/api/reports/consolidated/route.ts
  src/app/layout.tsx
  src/components/consolidated-view.tsx
  src/components/pwa/InstallPrompt.tsx
  src/components/pwa/NotificationPrompt.tsx
  src/components/pwa/ServiceWorkerRegistration.tsx
  src/components/pwa/TopBanner.tsx
  src/utils/pushNotifications.ts
Labels: bug, documentation, enhancement

#7 Fix bug pagination user
  src/app/(dashboard)/dashboard/users/page.tsx
  src/app/api/branches/route.ts
  src/app/api/reports/route.ts
  src/components/reports/PendingReport.tsx
  src/components/reports/ReportApproval.tsx
  src/components/reports/ViewReports.tsx
  src/hooks/useReportForm.ts
  src/hooks/useReports.ts
  src/lib/api/reports.ts
  src/lib/utils.ts
  src/types/reports.ts
Labels: bug, duplicate, enhancement
